### PR TITLE
Updated to IndexedDBShim v1.0.0

### PR DESCRIPTION
**Pull request by JamesMessinger**
This pull request updates the plug-in to the latest version of IndexedDBShim.   [**TONS** of bugs have been fixed](https://github.com/axemclion/IndexedDBShim/issues/178#issuecomment-93052746) in IndexedDBShim lately, specifically for Cordova-based mobile apps.

https://github.com/MSOpenTech/cordova-plugin-indexedDB/issues/5

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@BigstickCarpet__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by axemclion** [comment]
:+1:

**Comment by axemclion** [comment]
:+1:

**Comment by axemclion** [comment]
I will push it to Cordova plugins tomorrow.

**Comment by BigstickCarpet** [comment]
Thanks, Parashu.   I'll submit another PR tomorrow for the even-newer version.  :)

**Pull request merged**
